javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/game/Game.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/math/Vector3D.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/ability/Ability.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/shape/Shape.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/command/Command.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/parser/Parser.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/dispatch/Dispatch.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/shape/ShapeDynamic.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/shape/ShapeDynamicMonkey.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/game/GameMonkey.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/graphics/GraphicsMonkey.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/network/Network.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;lib/nifty-1.3.jar;lib/nifty-lwjgl-renderer-1.3-javadoc.jar;.;./src/" src/breslin/clientside/game/TestNiftyGui.java