javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/game/Game.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/math/Vector3D.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/ability/Ability.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/shape/Shape.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/command/Command.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/parser/Parser.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/bytebuffer/Dispatch.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/shape/ShapeDynamic.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/shape/ShapeDynamicMonkey.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/game/GameMonkey.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/graphics/GraphicsMonkey.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/network/Network.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/ability/rotation/AbilityRotation.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/ability/rotation/AbilityRotationState.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/ability/rotation/AbilityRotationStateMachine.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/ability/rotation/Global_ProcessTick_Rotation.java

javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/ability/move/AbilityMove.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/ability/move/AbilityMoveState.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/ability/move/AbilityMoveStateMachine.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/ability/move/Global_ProcessTick_Move.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/ability/move/Normal_ProcessTick_Move.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/ability/move/Catchup_ProcessTick_Move.java
javac -d build -cp "lib/jME3-lwjgl-natives.jar;lib/jMonkeyEngine3.jar;lib/lwjgl.jar;.;./src/" src/breslin/clientside/ability/move/Normal_InterpolateTick_Move.java